### ISSUE TITLE
Giving me full nmr +9203123456789 instead it should give +923123456789?

### ISSUE THREAD

**Issue by chnouman** [joielechong/CountryCodePicker#13] opened 2017-12-29 14:13 UTC
it was working perfectly on samsung s6 and oneplus but when i tried on samsung s4 mini it gives nmr in wrong format.

**Comment by joielechong** [comment] 2019-09-04 12:02
This is a late late response for your question. I can't answer it because the problem possibly related with the older version of the library. Please try using 2.4.1.

I'll close this issue for now. Please re-open if the issue is still persisted.

**Closed by joielechong** 2019-09-04 12:02 UTC
