### ISSUE TITLE
Change country name to my language

### ISSUE THREAD

**Issue by borjaruiz** [joielechong/CountryCodePicker#6] opened 2017-06-15 11:26 UTC
Hi, how can I change the name of a country to my own language? Thanks

**Comment by joielechong** [comment] 2017-06-15 12:49
Currently, the library only support English, Indonesian, France, and Russian. To change the language programatically, please visit this link: https://stackoverflow.com/a/35617428.

You can help the translation by changing the values from these resources files:
https://github.com/joielechong/CountryCodePicker/blob/master/library/src/main/res/values/strings_country.xml

https://github.com/joielechong/CountryCodePicker/blob/master/library/src/main/res/values/strings.xml

**Comment by joielechong** [comment] 2017-06-18 05:40
@borjaruiz: I'll close this issue and expect that the problem is solved. Fee free to reopen this issue if the problem still persist.

**Closed** 2017-06-18 05:40 UTC
