### ISSUE TITLE
Adding space after selecting country.

### ISSUE THREAD

**Issue by logan033** [joielechong/CountryCodePicker#40] opened 2019-01-31 13:04 UTC
Whenever I select any country, especially India. It makes a white space between CCP and edittext.
![screenshot_20190131-184124](https://user-images.githubusercontent.com/28998626/52056358-07506500-2588-11e9-8259-437a553164e7.png)
![screenshot_20190131-184139](https://user-images.githubusercontent.com/28998626/52056360-091a2880-2588-11e9-8a10-420ed530938a.png)

**Comment by joielechong** [comment] 2019-09-05 11:01
I can't reproduce the problem. Can you send a layout example with the issue?

I'll close this issue for now. Please kindly re-open the issue when you need.

**Closed by joielechong** 2019-09-05 11:01 UTC
