### ISSUE TITLE
App crashes  when clicked on CPP view

### ISSUE THREAD

**Issue by Chinmay-Kalmane** [joielechong/CountryCodePicker#49] opened 2019-04-09 07:19 UTC
When I click on CPP view, it crashes instead of opening the dialog. Here is the error:
 java.lang.NoSuchFieldError: No static field item_country_rly of type I in class Lcom/rilixtech/R$id; or its superclasses

**Comment by joielechong** [comment] 2019-04-11 16:27
This problem seem related with https://stackoverflow.com/q/29440321/4758255 and https://stackoverflow.com/q/36179847/4758255. Can you confirm that you didn't have the same view with `item_country_rly` id in one of your layout?

**Comment by joielechong** [comment] 2019-04-11 16:28
maybe I need to make the layout and id name special so that it won't clashed with user defined id.

**Comment by Chinmay-Kalmane** [comment] 2019-04-15 07:59
I can assure you that I don't have the same view with the same id in my
layouts.

**Comment by CorleoneAM** [comment] 2019-04-19 21:46
@Chinmay-Kalmane  Did u find a solution ?

**Comment by Chinmay-Kalmane** [comment] 2019-04-22 07:55
No I could not.

**Comment by joielechong** [comment] 2019-04-22 08:38
Can both of you confirm that the same problem is fixed with 2.3.3 version? If the problem still persist, please give me the exact details to reproduce the problem, including the device type and Android version.

**Comment by matangrolly** [comment] 2019-07-18 20:47
This can be reproduce if you have layout file with the same file name: item_country.xml

**Comment by joielechong** [comment] 2019-09-03 08:51
@matangrolly: Thank you for the confirmation. That should be the problem because the layout is being overrided. I have rename the layout for the 2.4.0 version. Please take a look for the new package and usage in README.

I'll close this issue for now. Please re-open if the problem still persisted.

**Closed by joielechong** 2019-09-03 08:51 UTC
