### ISSUE TITLE
flag thumbnail not showing

### ISSUE THREAD

**Issue by smodj** [joielechong/CountryCodePicker#14] opened 2018-01-21 21:36 UTC
![screenshot_1516570542](https://user-images.githubusercontent.com/8701960/35199210-3c8e1d3c-ff0c-11e7-88a5-e11d258ee0c3.png)

**Comment by joielechong** [comment] 2018-01-22 05:35
Can you tell me the step to reproduce the above problem?
What android version did you use, what support library, and what your target and build sdk?

**Comment by smodj** [comment] 2018-01-24 13:15
```
Add jitpack.io to your root build.gradle file:

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
Add library to your app build.gradle file then sync

dependencies {
    compile 'com.github.joielechong:countrycodepicker:2.1.5'
}
Add ccp view to xml layout

<com.rilixtech.CountryCodePicker
      android:id="@+id/ccp"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content" />
Add ccp object in Activity / Fragment

CountryCodePicker ccp;
Bind ccp from layout

ccp = (CountryCodePicker) findViewById(R.id.ccp);
That's it. Run the project and see the results.

```

I followed this, i am using updated api 27
with support library 27.0.2 version

**Comment by joielechong** [comment] 2018-05-11 11:00
I can't reproduce the problems. Please use the latest version. For the moment, I'll close this issue. Please reopen the issue if it's still persist.

**Closed by joielechong** 2018-05-11 11:00 UTC

**Comment by smodj** [comment] 2018-05-11 11:07
it's OK, i used another library.
