### ISSUE TITLE
French "Guyana"

### ISSUE THREAD

**Issue by BrilliantCorp** [joielechong/CountryCodePicker#42] opened 2019-02-27 09:56 UTC
The correct name for this French territory in English is "French Guiana". The form "Guyana" only applies to the independent English-speaking country to the west.

**Comment by joielechong** [comment] 2019-03-15 06:40
Thank you for the report! The issue is fixed in c1f6732a4ade91cbce541197289a81597621d8af commit.

**Closed by joielechong** 2019-03-15 06:40 UTC
